- name: Save Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "RateBot"
          git config --global user.email "bot@noreply.github.com"
          git add interest_rate_log.csv
          git commit -m "Daily Update" || exit 0
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
